<?php
$config['LANGUAGES_ITEMS'] = array(
	"site_wait_a_moment",
	"login",
	"validation_required_field",
	"validation_invalid_email",
	"site_accept",
	"site_cancel",
	"site_success",
	"site_error",
	"site_info",
	"site_data_saved_successfully",
	"site_create",
	"voting_created_successfully",
	"site_send",
	"voting_select_an_option",
	"voting_select_at_least_one_option",
	"voting_answer_saved_successfully"
);